### ISSUE TITLE
Design Navmenu to form the layout of our web page

### ISSUE THREAD

**Issue by blankdreams2** [UNLV-CS-GANG/gatekeeper#2]
Design a responsive menu bar at the top of the webpage where:

- [x] Include the Clerk login, ensure the Clerk system functioning
- [x] Include a Home -- About -- Contact routing page, leave spaces for future issues
- [ ] Organize, comment, and document UI libraries used in this issue.
- [ ] Include a hamburger icon or drop-down options (optional)

`This doesn't have to be perfect but something that is functioning at the time given.`

**Comment by Thienguen** [comment]
Design a responsive menu bar at the top of the webpage where:

- [ ] Include the Clerk login, ensure the Clerk system functioning
- [ ] Include a Home -- About -- Contact routing page, leave spaces for future issues
- [ ] Organize, comment, and document UI libraries used in this issue.
- [ ] Include a hamburger icon or drop-down options (optional)

`This doesn't have to be perfect but something that is functioning at the time given.`
