### ISSUE TITLE
Frontend: polish, update functionalities and organize web page

### ISSUE THREAD

**Issue by FabianCarrasco** [UNLV-CS-GANG/gatekeeper#20]

**Comment by Thienguen** [comment]
Write the requirements, what this issue trynna accomplish

- [ ] First thing
- [ ] Second thing
- [ ] Third thing

**Comment by FabianCarrasco** [comment]
# Polish the look of the event form and also the nav bar

- [x] Event Form
- [ ] Nav Bar
- [ ] Ensure Responsiveness
